services:
    db:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=myapp_development
        ports:
            - '5433:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 30s
          timeout: 10s
          retries: 3
        
    redis:
        image: redis:7.0.15-alpine
        ports:
        - '6380:6379'
        volumes:
        - redis_data:/data
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 30s
          timeout: 10s
          retries: 3
          
    web:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
        volumes:
            - .:/rails
            - bundle_cache:/usr/local/bundle
        ports:
            - "3000:3000"
        depends_on:
            db:
              condition: service_healthy
            redis:
              condition: service_healthy
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_development
            - REDIS_URL=redis://redis:6379/0
            - RAILS_ENV=development
            
    sidekiq:
        build: .
        command: bundle exec sidekiq
        volumes:
            - .:/rails
            - bundle_cache:/usr/local/bundle
        depends_on:
            db:
              condition: service_healthy
            redis:
              condition: service_healthy
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_development
            - REDIS_URL=redis://redis:6379/0
            - RAILS_ENV=development
            
    test:
        build: .
        command: bash -lc "./bin/rails db:prepare && bundle exec rspec"
        volumes:
            - .:/rails
            - bundle_cache:/usr/local/bundle
        depends_on:
            db:
              condition: service_healthy
            redis:
              condition: service_healthy
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_test
            - REDIS_URL=redis://redis:6379/0
            - RAILS_ENV=test
            
volumes:
    postgres_data:
    redis_data:
    bundle_cache: